### ISSUE TITLE
Pythonic installation as a step for better testing support

### ISSUE THREAD

**Issue by archie** [norwegianblues/parrot#2]
Parrot is currently depending on parrot-launcher (bash script) to set up appropriate environment variables necessary to run simulations. I believe it be appropriate to replace this with python script for the following reasons:
- the simulator core and web interface is confined to one os process
- easier to use when something doesn't work as expected 
- easier to extend and customise launch script (e.g., less messing around with global envs)
- in the long term could facilitate project and testing support for individual simulations
- encourages users to use virtualenv (also implies a proper setup.py script)

I have a draft, currently incompatible, that I can bring up to date.

**Comment by persquare** [comment]
Please do!

**Comment by archie** [comment]
Closed by #3.
